### ISSUE TITLE
Out-of-box webflow 1.0 RC4 sample not working on TOMCAT 5.5.17 [SWF-194]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#1108]
**[David Jiao](https://jira.spring.io/secure/ViewProfile.jspa?name=djiao)** opened **[SWF-194](https://jira.spring.io/browse/SWF-194?redirect=false)** and commented

Two sample application (phonebook, and birthdate) built and executed. Both generate an exception page when starting the webflow (the first step).

---

HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoClassDefFoundError
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:846)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:736)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:396)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:350)
javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
javax.servlet.http.HttpServlet.service(HttpServlet.java:802)

root cause

java.lang.NoClassDefFoundError
org.springframework.webflow.util.RandomGuidUidGenerator.generateUid(RandomGuidUidGenerator.java:51)
org.springframework.webflow.conversation.impl.SessionBindingConversationManager.beginConversation(SessionBindingConversationManager.java:80)
org.springframework.webflow.execution.repository.support.AbstractConversationFlowExecutionRepository.generateKey(AbstractConversationFlowExecutionRepository.java:89)
org.springframework.webflow.executor.FlowExecutorImpl.launch(FlowExecutorImpl.java:202)
org.springframework.webflow.executor.support.FlowRequestHandler.handleFlowRequest(FlowRequestHandler.java:131)
org.springframework.webflow.executor.mvc.FlowController.handleRequestInternal(FlowController.java:169)
org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:45)
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:806)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:736)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:396)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:350)
javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
javax.servlet.http.HttpServlet.service(HttpServlet.java:802)

note The full stack trace of the root cause is available in the Apache Tomcat/5.5.17 logs.

---

**Affects:** 1.0 RC4
