### ISSUE TITLE
swf-sellitem-jsf sample application don't work with a 2.4 Servlet Container [SWF-399]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#1239]
**[Agim Emruli](https://jira.spring.io/secure/ViewProfile.jspa?name=agim)** opened **[SWF-399](https://jira.spring.io/browse/SWF-399?redirect=false)** and commented

Hello,

if I run the sample application inside a servlet 2.4/jsp 2.0 container, the swf-sellitem-jsf sample application won't start.
The original error is a ClassNotFoundException

java.lang.NoClassDefFoundError: javax/el/ELResolver

After adding the el-api.jar to the WEB-INF/lib directory i get the following error

java.lang.NoSuchMethodError: javax.servlet.jsp.JspFactory.getJspApplicationConte
xt(Ljavax/servlet/ServletContext;)Ljavax/servlet/jsp/JspApplicationContext;
at org.apache.myfaces.webapp.DefaultFacesInitializer.initFaces(DefaultFacesInitializer.java:102)
at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:57)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3763)

Also if i use the jsf ri implementation, the application still won't work.
I get the follwoing exception if i remove the myfaces implementation (remove the jar and the listener inside the web.xml) and replace them with a jsf 1.2 RI.

javax.servlet.ServletException: javax/servlet/jsp/tagext/JspIdConsumer
org.apache.jasper.servlet.JspServlet.service(JspServlet.java:272)
javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
com.sun.faces.context.ExternalContextImpl.dispatch(ExternalContextImpl.java:428)
com.sun.faces.application.ViewHandlerImpl.executePageToBuildView(ViewHandlerImpl.java:444)
com.sun.faces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:116)
com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:106)

The Class JspIdConsumer is avaiable in the JSP2.1 Spec. Is there any real need for JSF 1.2 inside this sample application ?
I think JSF 1.1 would be good enough for sellitem-jsf.

---

**Affects:** 2.0 M1
