### ISSUE TITLE
Allow JSF sample application to work on Servlet 2.4 Container like Tomcat 5.5  [SWF-400]

### ISSUE THREAD

**Issue by spring-operator** [spring-projects/spring-webflow#1240]
**[Agim Emruli](https://jira.spring.io/secure/ViewProfile.jspa?name=agim)** opened **[SWF-400](https://jira.spring.io/browse/SWF-400?redirect=false)** and commented

Hello,

while running the swf-booking-jsf sample inside tomcat 5.5.20, i have to make a few changes inside the sample application, because it doesn't work out-of-the-box on tomcat 5.520.

1.) java.lang.NoClassDefFoundError: javax/el/ExpressionFactory
Because the el Implementation is only available in tomcat 6.0 (or later)  i have added the el-api.jar into the WEB-INF/lib dorectory of the application.
The jar file is located in the directory projects\spring-faces\lib\buildtime inside the spring webflow distribution.

2.) java.lang.NoSuchMethodError: javax.servlet.jsp.JspFactory.getJspApplicationContext(Ljavax/servlet/ServletContext;)Ljavax/servlet/jsp/JspApplicationContext;
at org.apache.myfaces.webapp.DefaultFacesInitializer.initFaces(DefaultFacesInitializer.java:102)

MyFaces is the JSF Implementation which is delivered along with the sample application. Even if the sample doesn't use JSP but facelets, myfaces has some dependency on jsp 2.1 APIs.
So i removed the myfaces-impl and myfaces-api jar from the WEB-INF lib directory, and replaced it with the SUN JSF 1.2 RI implementation. Which can be downloaded here:
https://javaserverfaces.dev.java.net/files/documents/1866/58375/jsf-1_2_04-p02.zip

3.) java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl
This error happens because facelets seems to have some dependencies on the sun el implementation. To solvie this i have downloaded the implementation from the maven repo and moved into the WEB-INF/lib Folder. http://download.java.net/maven/1/el-impl/jars/

I think the the Servlet 2.4 compability is important, so i think that we should distribute swf-booking-jsf with the sun-ri implementation. (Or use jsf 1.1 if its posible)

---

**Affects:** 2.0 M1

**Issue Links:**
- #1249 Restore JSF 1.1 compatability for Web Flow 2.0
  (_**"depends on"**_)
